curl -X POST http://localhost:8080/take/clubs -H "Content-Type: application/json" -d "{\"name\":\"Real Madrid CF\",\"location\":\"Madrid\",\"dateOfCreation\":\"1902-01-01\"}"
curl -X POST http://localhost:8080/take/clubs -H "Content-Type: application/json" -d "{\"name\":\"Club Atletico de Madrid\",\"location\":\"Madrid\",\"dateOfCreation\":\"1903-04-26\"}"
curl -X POST http://localhost:8080/take/clubs -H "Content-Type: application/json" -d "{\"name\":\"FC Barcelona\",\"location\":\"Barcelona\",\"dateOfCreation\":\"1899-01-01\"}"
curl -X POST http://localhost:8080/take/clubs -H "Content-Type: application/json" -d "{\"name\":\"Sevilla FC\",\"location\":\"Sevilla\",\"dateOfCreation\":\"1890-01-25\"}"

curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Thibaut\",\"surname\":\"Courtois\",\"number\":1,\"position\":\"Goalkeeper\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Andriy\",\"surname\":\"Lunin\",\"number\":13,\"position\":\"Goalkeeper\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Eder\",\"surname\":\"Militao\",\"number\":3,\"position\":\"Centre-Back\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Antonio\",\"surname\":\"Rudiger\",\"number\":22,\"position\":\"Centre-Back\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"David\",\"surname\":\"Alaba\",\"number\":4,\"position\":\"Centre-Back\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Nacho\",\"surname\":\"Fernandez\",\"number\":6,\"position\":\"Centre-Back\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Ferland\",\"surname\":\"Mendy\",\"number\":23,\"position\":\"Left-Back\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Fran\",\"surname\":\"Garcia\",\"number\":20,\"position\":\"Left-Back\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Daniel\",\"surname\":\"Carvajal\",\"number\":2,\"position\":\"Right-Back\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Aurelien\",\"surname\":\"Tchouameni\",\"number\":18,\"position\":\"Defensive Midfield\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Federico\",\"surname\":\"Valverde\",\"number\":15,\"position\":\"Central Midfield\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Eduardo\",\"surname\":\"Camavinga\",\"number\":12,\"position\":\"Central Midfield\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Dani\",\"surname\":\"Ceballos\",\"number\":19,\"position\":\"Central Midfield\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Jude\",\"surname\":\"Bellingham\",\"number\":5,\"position\":\"Attacking Midfield\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Brahim\",\"surname\":\"Diaz\",\"number\":21,\"position\":\"Attacking Midfield\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Arda\",\"surname\":\"Guler\",\"number\":24,\"position\":\"Attacking Midfield\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Nico\",\"surname\":\"Paz\",\"number\":32,\"position\":\"Attacking Midfield\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Vinicius\",\"surname\":\"Junior\",\"number\":7,\"position\":\"Left Winger\",\"clubId\":1}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Rodrygo\",\"surname\":\"Goes\",\"number\":11,\"position\":\"Right Winger\",\"clubId\":1}"

curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Jan\",\"surname\":\"Oblak\",\"number\":13,\"position\":\"Goalkeeper\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Horatiu\",\"surname\":\"Moldovan\",\"number\":1,\"position\":\"Goalkeeper\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Jose Maria\",\"surname\":\"Gimenez\",\"number\":2,\"position\":\"Centre-Back\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Axel\",\"surname\":\"Witsel\",\"number\":20,\"position\":\"Centre-Back\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Stefan\",\"surname\":\"Savic\",\"number\":15,\"position\":\"Centre-Back\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Reinildo\",\"surname\":\"Mandava\",\"number\":23,\"position\":\"Left-Back\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Nahuel\",\"surname\":\"Molina\",\"number\":16,\"position\":\"Right-Back\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Cesar\",\"surname\":\"Azpilicueta\",\"number\":3,\"position\":\"Right-Back\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Rodrigo\",\"surname\":\"de Paul\",\"number\":5,\"position\":\"Central Midfield\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Marcos\",\"surname\":\"Llorente\",\"number\":14,\"position\":\"Central Midfield\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Arthur\",\"surname\":\"Vermeeren\",\"number\":18,\"position\":\"Central Midfield\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Pablo\",\"surname\":\"Barrios\",\"number\":24,\"position\":\"Central Midfield\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Jorge\",\"surname\":\"Koke\",\"number\":6,\"position\":\"Central Midfield\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Saul\",\"surname\":\"Niguez\",\"number\":8,\"position\":\"Central Midfield\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Thomas\",\"surname\":\"Lemar\",\"number\":11,\"position\":\"Attacking Midfield\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Samuel\",\"surname\":\"Lino\",\"number\":12,\"position\":\"Left Winger\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Rodrigo\",\"surname\":\"Riquelme\",\"number\":17,\"position\":\"Left Winger\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Angel\",\"surname\":\"Correa\",\"number\":10,\"position\":\"Right Winger\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Antoine\",\"surname\":\"Griezmann\",\"number\":7,\"position\":\"Centre-Forward\",\"clubId\":2}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Alvaro\",\"surname\":\"Morata\",\"number\":19,\"position\":\"Centre-Forward\",\"clubId\":2}"

curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Marc-Andre\",\"surname\":\"ter Stegen\",\"number\":1,\"position\":\"Goalkeeper\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Inaki\",\"surname\":\"Pena\",\"number\":13,\"position\":\"Goalkeeper\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Ander\",\"surname\":\"Astralaga\",\"number\":26,\"position\":\"Goalkeeper\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Ronald\",\"surname\":\"Araujo\",\"number\":4,\"position\":\"Centre-Back\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Jules\",\"surname\":\"Kounde\",\"number\":23,\"position\":\"Centre-Back\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Andreas\",\"surname\":\"Christensen\",\"number\":15,\"position\":\"Centre-Back\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Pau\",\"surname\":\"Cubarsi\",\"number\":33,\"position\":\"Centre-Back\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Inigo\",\"surname\":\"Martinez\",\"number\":5,\"position\":\"Centre-Back\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Alejandro\",\"surname\":\"Balde\",\"number\":3,\"position\":\"Left-Back\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Hector\",\"surname\":\"Fort\",\"number\":39,\"position\":\"Right-Back\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Oriol\",\"surname\":\"Romeu\",\"number\":18,\"position\":\"Defensive Midfield\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Pablo\",\"surname\":\"Gavi\",\"number\":6,\"position\":\"Central Midfield\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Pedro\",\"surname\":\"Pedri\",\"number\":8,\"position\":\"Central Midfield\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Frenkie\",\"surname\":\"de Jong\",\"number\":21,\"position\":\"Central Midfield\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Fermin\",\"surname\":\"Lopez\",\"number\":16,\"position\":\"Central Midfield\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Ilkay\",\"surname\":\"Gundogan\",\"number\":22,\"position\":\"Central Midfield\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Ferran\",\"surname\":\"Torres\",\"number\":7,\"position\":\"Left Winger\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Lamine\",\"surname\":\"Yamal\",\"number\":27,\"position\":\"Right Winger\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Raphael\",\"surname\":\"Raphinha\",\"number\":11,\"position\":\"Right Winger\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Vitor\",\"surname\":\"Roque\",\"number\":19,\"position\":\"Centre-Forward\",\"clubId\":3}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Robert\",\"surname\":\"Lewandowski\",\"number\":9,\"position\":\"Centre-Forward\",\"clubId\":3}"

curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Orjan\",\"surname\":\"Nyland\",\"number\":13,\"position\":\"Goalkeeper\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Marko\",\"surname\":\"Dmitrovic\",\"number\":1,\"position\":\"Goalkeeper\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Loic\",\"surname\":\"Bade\",\"number\":22,\"position\":\"Centre-Back\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Kike\",\"surname\":\"Salas\",\"number\":2,\"position\":\"Centre-Back\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Marcos\",\"surname\":\"Marcao\",\"number\":23,\"position\":\"Centre-Back\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Nemanja\",\"surname\":\"Gudelj\",\"number\":6,\"position\":\"Centre-Back\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Tanguy\",\"surname\":\"Nianzou\",\"number\":14,\"position\":\"Centre-Back\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Adria\",\"surname\":\"Pedrosa\",\"number\":3,\"position\":\"Left-Back\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Marcos\",\"surname\":\"Acuna\",\"number\":19,\"position\":\"Left-Back\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Juanlu\",\"surname\":\"Sanchez\",\"number\":26,\"position\":\"Right-Back\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Jesus\",\"surname\":\"Navas\",\"number\":16,\"position\":\"Right-Back\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Djibril\",\"surname\":\"Sow\",\"number\":18,\"position\":\"Central-Midfield\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Joan\",\"surname\":\"Jordan\",\"number\":8,\"position\":\"Central-Midfield\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Manu\",\"surname\":\"Bueno\",\"number\":28,\"position\":\"Central-Midfield\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Lucas\",\"surname\":\"Ocampos\",\"number\":5,\"position\":\"Left Winger\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Dodi\",\"surname\":\"Lukebakio\",\"number\":11,\"position\":\"Right Winger\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Jesus\",\"surname\":\"Suso\",\"number\":7,\"position\":\"Right Winger\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Adnan\",\"surname\":\"Januzaj\",\"number\":25,\"position\":\"Right Winger\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Youssef\",\"surname\":\"En-Nesyri\",\"number\":15,\"position\":\"Centre-Forward\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Isaac\",\"surname\":\"Romero\",\"number\":20,\"position\":\"Centre-Forward\",\"clubId\":4}"
curl -X POST http://localhost:8080/take/players -H "Content-Type: application/json" -d "{\"name\":\"Rafa\",\"surname\":\"Mir\",\"number\":9,\"position\":\"Centre-Forward\",\"clubId\":4}"

curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Santiago Bernabeu\",\"date\":\"2024-01-01\",\"players\":[5,7,8,9,10,14,15,16,18,22,23,24,26,28,29,30,32,36,37,38,42,43],\"homeClubId\":1,\"awayClubId\":2}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Camp Nou\",\"date\":\"2024-01-02\",\"players\":[44,47,48,49,52,55,56,57,61,62,64,66,67,70,71,73,76,78,79,80,81,84],\"homeClubId\":3,\"awayClubId\":4}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Santiago Bernabeu\",\"date\":\"2024-01-03\",\"players\":[6,7,8,9,10,14,15,16,18,22,23,44,47,48,49,52,55,56,57,60,62,63],\"homeClubId\":1,\"awayClubId\":3}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Estadio Metropolitano\",\"date\":\"2024-01-04\",\"players\":[24,26,28,29,30,32,36,37,38,41,43,66,68,70,71,73,76,78,79,80,81,84],\"homeClubId\":2,\"awayClubId\":4}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Santiago Bernabeu\",\"date\":\"2024-01-05\",\"players\":[5,7,8,9,13,14,15,16,18,22,23,65,67,70,71,73,76,78,79,80,81,85],\"homeClubId\":1,\"awayClubId\":4}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Camp Nou\",\"date\":\"2024-01-06\",\"players\":[44,47,48,49,52,55,56,57,59,62,64,24,26,28,29,30,32,36,37,41,42,43],\"homeClubId\":3,\"awayClubId\":2}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Estadio Metropolitano\",\"date\":\"2024-01-07\",\"players\":[5,7,8,10,12,14,15,16,18,22,23,24,26,28,29,30,32,36,37,39,40,43],\"homeClubId\":2,\"awayClubId\":1}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Estadio Ramon Sanchez-Pizjuan\",\"date\":\"2024-01-08\",\"players\":[45,47,48,49,53,55,56,57,61,62,64,66,67,70,71,73,77,78,79,80,82,84],\"homeClubId\":4,\"awayClubId\":3}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Camp Nou\",\"date\":\"2024-01-09\",\"players\":[5,7,8,9,10,14,15,16,19,21,23,44,47,48,49,50,51,56,57,60,62,63],\"homeClubId\":3,\"awayClubId\":1}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Estadio Ramon Sanchez-Pizjuan\",\"date\":\"2024-01-10\",\"players\":[24,27,28,29,30,32,36,37,38,41,43,66,68,70,72,74,76,78,79,80,81,84],\"homeClubId\":4,\"awayClubId\":2}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Estadio Ramon Sanchez-Pizjuan\",\"date\":\"2024-01-11\",\"players\":[5,7,8,10,13,14,15,16,18,21,23,65,67,70,71,72,76,78,79,80,82,85],\"homeClubId\":4,\"awayClubId\":1}"
curl -X POST http://localhost:8080/take/matches -H "Content-Type: application/json" -d "{\"location\":\"Estadio Metropolitano\",\"date\":\"2024-01-12\",\"players\":[44,47,48,49,51,55,56,57,60,61,64,24,26,28,29,30,32,36,37,39,40,43],\"homeClubId\":2,\"awayClubId\":3}"

curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":12,\"ownGoal\":false,\"scorerId\":23,\"assistantId\":22,\"matchId\":86}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":25,\"ownGoal\":false,\"scorerId\":22,\"assistantId\":23,\"matchId\":86}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":74,\"ownGoal\":false,\"scorerId\":18,\"assistantId\":16,\"matchId\":86}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":10,\"ownGoal\":false,\"scorerId\":84,\"assistantId\":81,\"matchId\":87}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":89,\"ownGoal\":false,\"scorerId\":62,\"assistantId\":64,\"matchId\":87}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":35,\"ownGoal\":false,\"scorerId\":62,\"assistantId\":63,\"matchId\":88}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":38,\"ownGoal\":false,\"scorerId\":16,\"assistantId\":15,\"matchId\":88}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":41,\"ownGoal\":false,\"scorerId\":23,\"assistantId\":22,\"matchId\":88}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":65,\"ownGoal\":false,\"scorerId\":23,\"assistantId\":22,\"matchId\":88}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":90,\"ownGoal\":false,\"scorerId\":22,\"assistantId\":23,\"matchId\":88}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":49,\"ownGoal\":true,\"scorerId\":29,\"assistantId\":78,\"matchId\":89}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":15,\"ownGoal\":false,\"scorerId\":15,\"assistantId\":18,\"matchId\":90}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":24,\"ownGoal\":true,\"scorerId\":5,\"assistantId\":76,\"matchId\":90}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":45,\"ownGoal\":false,\"scorerId\":23,\"assistantId\":18,\"matchId\":90}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":61,\"ownGoal\":false,\"scorerId\":9,\"assistantId\":16,\"matchId\":90}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":89,\"ownGoal\":false,\"scorerId\":85,\"assistantId\":81,\"matchId\":90}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":16,\"ownGoal\":true,\"scorerId\":24,\"assistantId\":23,\"matchId\":92}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":85,\"ownGoal\":false,\"scorerId\":36,\"assistantId\":37,\"matchId\":92}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":36,\"ownGoal\":false,\"scorerId\":82,\"assistantId\":84,\"matchId\":93}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":74,\"ownGoal\":false,\"scorerId\":82,\"assistantId\":80,\"matchId\":93}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":2,\"ownGoal\":false,\"scorerId\":21,\"assistantId\":23,\"matchId\":94}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":8,\"ownGoal\":false,\"scorerId\":62,\"assistantId\":63,\"matchId\":94}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":18,\"ownGoal\":false,\"scorerId\":63,\"assistantId\":62,\"matchId\":94}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":48,\"ownGoal\":false,\"scorerId\":57,\"assistantId\":56,\"matchId\":94}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":14,\"ownGoal\":false,\"scorerId\":32,\"assistantId\":36,\"matchId\":95}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":27,\"ownGoal\":false,\"scorerId\":32,\"assistantId\":36,\"matchId\":95}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":48,\"ownGoal\":false,\"scorerId\":74,\"assistantId\":76,\"matchId\":95}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":72,\"ownGoal\":false,\"scorerId\":76,\"assistantId\":78,\"matchId\":95}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":17,\"ownGoal\":false,\"scorerId\":18,\"assistantId\":23,\"matchId\":96}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":31,\"ownGoal\":false,\"scorerId\":18,\"assistantId\":21,\"matchId\":96}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":87,\"ownGoal\":false,\"scorerId\":21,\"assistantId\":23,\"matchId\":96}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":90,\"ownGoal\":false,\"scorerId\":23,\"assistantId\":14,\"matchId\":96}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":11,\"ownGoal\":true,\"scorerId\":57,\"assistantId\":43,\"matchId\":97}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":15,\"ownGoal\":false,\"scorerId\":43,\"assistantId\":40,\"matchId\":97}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":24,\"ownGoal\":true,\"scorerId\":40,\"assistantId\":64,\"matchId\":97}"
curl -X POST http://localhost:8080/take/goals -H "Content-Type: application/json" -d "{\"minute\":65,\"ownGoal\":false,\"scorerId\":37,\"assistantId\":39,\"matchId\":97}"

curl -X PUT http://localhost:8080/take/matches/86 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/87 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/88 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/89 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/90 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/91 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/92 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/93 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/94 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/95 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/96 -H "Content-Type: application/json" -d "{\"played\": true}"
curl -X PUT http://localhost:8080/take/matches/97 -H "Content-Type: application/json" -d "{\"played\": true}"





